version: "3.7"

services:
    blog:
        build: ./../../blog
        image: serbanblebea/go-blog:v0.2
        container_name: blog
        ports:
            - 8088:8088
        environment:
            HTTP_PORT: 8088
        restart: on-failure
