@host=192.168.50.11:30011

POST http://{{host}}/hello
Content-Type: application/json

{
    "name": "Serban",
    "age": 30,
    "template": "Hello! My name is %s and I am %d yo"
}

###

GET http://{{host}}/


###

GET http://{{host}}/article/first-article


### 
GET https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=77y35i071ogn31&redirect_uri=https://mihaiblebea.com&state=abcd&scope=w_member_social,r_liteprofile