variable "do_token" {
    description = "digital ocean api token"
    type        = string
}

variable "load_balancer_name" {}

variable "droplet_id" {}

# variable "loadbalancer_ip" {
#     description = "ip of the load balancer generated by the nginx ingress"
# }


