# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: Test blog Go app
      working-directory: ./blog
      run: go test ./...

    - name: Build and push Docker images - Blog
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: serbanblebea/go-blog
        tags: ${{ github.sha }}
        path: ./blog

    - name: Build and push Docker images - Broadcast
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: serbanblebea/go-broadcast
        tags: ${{ github.sha }}
        path: ./broadcast

    - name: Build and push Docker images - List
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: serbanblebea/go-list
        tags: ${{ github.sha }}
        path: ./list
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.1.0
      with:
        cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
        terraform_version: 0.12.20
    
    - name: Terraform Init
      run: terraform init
      working-directory: ./deploy/terraform

    - name: Terraform Get
      run: terraform get
      working-directory: ./deploy/terraform
      
    - name: Terraform Plan
      working-directory: ./deploy/terraform
      run: terraform plan
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
        TF_VAR_blog_image: serbanblebea/go-blog:${{ github.sha }}
        TF_VAR_broadcast_image: serbanblebea/go-broadcast:${{ github.sha }}
        TF_VAR_linkedin_access_token: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        TF_VAR_twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TF_VAR_twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TF_VAR_twitter_token: ${{ secrets.TWITTER_TOKEN }}
        TF_VAR_twitter_token_secret: ${{ secrets.TWITTER_TOKEN_SECRET }}
        TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
        TF_VAR_google_search_console_code: ${{ secrets.GOOGLE_SEARCH_CONSOLE_CODE }}
        TF_VAR_pocket_consumer_key: ${{ secrets.POCKET_CONSUMER_KEY }}
        TF_VAR_pocket_access_token: ${{ secrets.POCKET_ACCESS_TOKEN }}
        TF_VAR_aws_domain_verification_token: ${{ secrets.AWS_DOMAIN_VERIFICATION_TOKEN }}
        TF_VAR_aws_domain_key_set: ${{ secrets.AWS_DOMAIN_KEY_SET }}
        TF_VAR_list_image: serbanblebea/go-list:${{ github.sha }}
        TF_VAR_google_credentials_file: ${{ secrets.GOOGLE_CREDENTIALS_FILE }}
        TF_VAR_google_token_file: ${{ secrets.GOOGLE_TOKEN_FILE }}
        TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Apply
      working-directory: ./deploy/terraform
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
        TF_VAR_blog_image: serbanblebea/go-blog:${{ github.sha }}
        TF_VAR_broadcast_image: serbanblebea/go-broadcast:${{ github.sha }}
        TF_VAR_linkedin_access_token: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        TF_VAR_twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TF_VAR_twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TF_VAR_twitter_token: ${{ secrets.TWITTER_TOKEN }}
        TF_VAR_twitter_token_secret: ${{ secrets.TWITTER_TOKEN_SECRET }}
        TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
        TF_VAR_google_search_console_code: ${{ secrets.GOOGLE_SEARCH_CONSOLE_CODE }}
        TF_VAR_pocket_consumer_key: ${{ secrets.POCKET_CONSUMER_KEY }}
        TF_VAR_pocket_access_token: ${{ secrets.POCKET_ACCESS_TOKEN }}
        TF_VAR_aws_domain_verification_token: ${{ secrets.AWS_DOMAIN_VERIFICATION_TOKEN }}
        TF_VAR_aws_domain_key_set: ${{ secrets.AWS_DOMAIN_KEY_SET }}
        TF_VAR_list_image: serbanblebea/go-list:${{ github.sha }}
        TF_VAR_google_credentials_file: ${{ secrets.GOOGLE_CREDENTIALS_FILE }}
        TF_VAR_google_token_file: ${{ secrets.GOOGLE_TOKEN_FILE }}
        TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}