name: repo-event-taint-lb

on:
  repository_dispatch:
      types: taint-lb

jobs:
  taint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.1.0
      with:
        cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
        terraform_version: 0.12.20
    
    - name: Terraform Init
      run: terraform init
      working-directory: ./deploy/terraform
    
    - name: Terraform Get
      run: terraform get
      working-directory: ./deploy/terraform
    
    - name: Terraform Taint
      run: terraform taint data.digitalocean_loadbalancer.load_balancer
      working-directory: ./deploy/terraform
